#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

# Update package index
apt-get update -y

# Install nginx
apt-get install nginx -y

# Replace default nginx configuration to return "Hello World!" at the root
echo 'server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                return 200 "Hello World!\n";
        }
}' > /etc/nginx/sites-available/default

# Restart nginx without systemctl
service nginx restart

# Check if Nginx is installed
if [ $(dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo "Nginx installation failed."
else
    echo "Nginx is installed."
fi

# Check if Nginx is listening on port 80
if [ $(netstat -tuln | grep -c ":80 ") -eq 0 ]; then
    echo "Nginx is not listening on port 80."
else
    echo "Nginx is listening on port 80."
fi

# Check if querying root returns "Hello World!"
response=$(curl -s localhost)
if [ "$response" == "Hello World!" ]; then
    echo "Nginx returns 'Hello World!' at its root."
else
    echo "Nginx doesn't return 'Hello World!' at its root."
fi
