#!/usr/bin/env bash
# This script displays the time from 0:00 to 1:59 with "Hour: x" before each hour

hour=0

while [ "$hour" -le 1 ]; do
    echo "Hour: $hour"
    
    minute=0
    while [ "$minute" -le 59 ]; do
        if [ "$minute" -lt 10 ]; then
            echo "$minute"
        else
            echo "$minute"
        fi
        ((minute++))
    done
    
    ((hour++))
done | head -n 70
